# Warning! Each maintenance playbook shall run without generated vars being present!
# It should fetch this information as needed, without the need to run whole infra step.
- hosts: localhost
  connection: local
  roles:
    - role: cs.aws-rds-gfs-backup
      rds_gfs_instance_id: "{{ aws_rds_instance_name }}"
