- hosts: all
  connection: local
  gather_facts: no
  tags: always
  tasks:
    - name: Create virtual inventory group with hosts limited to current project/env (AWS)
      group_by: 
        key: current
      when: aws_use and inventory_hostname in groups[mageops_app_host_group]

    - name: Create virtual inventory group with all hosts (non-AWS)
      group_by: 
        key: current 
      when: not aws_use

