- hosts: localhost
  connection: local
  roles:
    - role: cs.aws-node-facts

    - role: cs.aws-create-ami
      ami_description: "{{ mageops_project | capitalize }} {{ mageops_environment | capitalize }} App Node ({{ ansible_date_time.iso8601 }})"
      ami_instance_id: "{{ aws_app_builder_node_instance.instance_id }}"
      ami_name: "{{ mageops_app_name }}-app-{{ ansible_date_time.epoch }}"
      ami_tags: "{{ aws_tags_role_app }}"

    - role: cs.aws-node-state
      node_state_target: absent
      node_state_instance_tags: >-
        {{
            aws_tags_base | combine(
                aws_tags_role_app,
                aws_tags_role_app_builder
            )
        }}
      when: aws_ami_build_terminate_builder