# This brew formula is for exactly unison 4.48.4
unison_brew_package: https://raw.githubusercontent.com/Homebrew/homebrew-core/943cfcfc831e98dc37602eeeeb73b07a0e3721e1/Formula/unison.rb
unison_project_name: "{{ mageops_project }}"
unison_port: 5566
unison_guest_ip: "{{ hostvars[groups['vagrant'][0]]['ansible_host'] }}"
unison_local_path: "{{ playbook_dir }}/../projects/{{ unison_project_name }}"
unison_remote_path: "/{{ unison_project_name }}"
unison_sync_excludes:
    - ".idea"
    - ".DS_Store"
    - "._.DS_Store"
    - "node_modules"
    - ".php_cs.cache"
