- shell: "mysqladmin -u{{ mysql_root_user }} -p{{ mysql_root_pass }} reload"

- name: Ensure MySQL root user has public access
  mysql_user:
    name: "{{ mysql_root_user }}"
    host: "%"
    password: "{{ mysql_root_pass }}"
    priv: "*.*:ALL"
    state: present
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_pass }}"

- shell: "mysqladmin -u{{ mysql_root_user }} -p{{ mysql_root_pass }} reload"