# We need to do this, because there's a slight chance cf will hit old server
# using new deployment asset versions, because there's a period of time old and new
# app nodes are running at the same time. The result would be that old assets are
# cached at the new urls (basically the static asset version in the url is ignored by magento).

- name: Invalidate cloudfront magento static assets
  cloudfront_invalidation:
    distribution_id: "{{ aws_cloudfront_distribution_id }}"
    caller_reference: "deploy-{{ ansible_date_time.iso8601_basic_short }}"
    target_paths:
        - '/static/*'
  when: aws_cloudfront_distribution_id is defined and aws_cloudfront_distribution_id != ''