- name: Make sure directories exist
  file:
    path: "{{ item }}"
    state: directory
    follow: yes
    mode: 0755
  with_items:
    - "{{ https_termination_certificate_dir }}"
    - "{{ https_termination_private_dir }}"
    - "{{ https_termination_csr_dir }}"