- name: "Executing deploy hook: {{ deploy_hook_name }}"
  include_tasks: hook-action-{{ deploy_hook_action_type }}.yml
  vars:
    deploy_hook_action_type: >-
      {{
          'tasks-from-role' if (deploy_hook_action.tasks_from is defined and deploy_hook_action.role is defined) else
            'role' if (deploy_hook_action.role is defined) else
              'tasks' if (deploy_hook_action.tasks is defined) 
      }}
    deploy_hook_action_name: "{{ deploy_hook_action.name | default(deploy_hook_action.role | default(deploy_hook_action.tasks)) }}"
  when: >
    deploy_hook_action.role is defined
    or deploy_hook_action.tasks is defined 
    or (
      deploy_hook_action.when is defined
      and deploy_hook_action.when | bool
    )
  loop: "{{ deploy_hook_actions }}"
  loop_control:
    loop_var: deploy_hook_action
