- name: Create policy that allows user to add IAM Roles to EC2 instances
  iam_managed_policy:
    policy_name: "{{ aws_iam_policy_ec2_assign_iam_role }}"
    policy_description: Allow to assign IAM roles to EC2 Instances
    policy: "{{ lookup('template', 'pass_role_to_ec2.policy.json') }}"
    state: present

- name: Create Lambda access policy
  iam_managed_policy:
    policy_name: "{{ aws_iam_policy_lambda_access }}"
    policy_description: Allow to maniuplate lambdas
    policy: "{{ lookup('template', 'lambda_access.policy.json') }}"
    state: present


