- name: Check if there was old elasticsearch installed
  stat:
    path: /etc/elasticsearch/node1
  register: _mageops_es_deprecated

- name: Clean up after old elasticsearch installation
  block:
    - name: Make sure old elasticsearch service is stopped
      service:
        name: node1_elasticsearch
        state: stopped
        enabled: no

    - name: Remove old elasticsearch package
      yum:
        name: elasticsearch
        state: absent

    - name: Make sure es repo, package and provisioning leftovers are removed
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/elasticsearch/node1
        - /opt/elasticsearch
        - /usr/lib/systemd/system/node1_elasticsearch.service
        - /etc/yum.repos.d/elasticsearch-5.x.repo

    - name: Remove elasticsearch versionlock
      command: yum versionlock delete elasticsearch
      register: _mageops_es_old_vlock
      changed_when: _mageops_es_old_vlock.rc == 0
      failed_when: false

    - name: Clean yum repo metadata
      command: yum clean metadata
      args:
        warn: no
      changed_when: false
  when: _mageops_es_deprecated.stat.exists is defined and _mageops_es_deprecated.stat.exists

