- name: Set deploy release id
  block:
    - name: Compute deploy release id
      shell: date +%Y%m%d%H%M%S
      register: _deploy_release_id_result

    - name: Register deploy release id
      set_fact:
        deploy_release_id: "{{ deploy_release_id_result.stdout }}"
  when: deploy_release_id is not defined

- name: Set path of next realease
  set_fact:
    deploy_next_release_path: "{{ deploy_releases_dir }}/{{ deploy_release_id }}"

- name: Check if current release exists
  stat:
    path: "{{ deploy_current_release_dir }}"
    follow: true
  register: _deploy_current_release_dir_check

- name: Get current release path
  block:
    - name: Get real path of the current release
      command: "readlink -f {{ deploy_current_release_dir }}"
      register: _deploy_current_release_dir_readlink

    - name: Set path of current release
      set_fact:
        deploy_current_release_path: "{{ _deploy_current_release_dir_readlink.stdout }}"
  when: _deploy_current_release_dir_check.stat.isdir is defined and _deploy_current_release_dir_check.stat.isdir

- name: Set app user
  block:
    - name: Obtain remote app user
      shell: whoami
      register: _deploy_app_user_check

    - name: Set remote app user
      set_fact:
        deploy_app_user: "{{ _deploy_app_user_check.stdout }}"

    - name: Set remote app group
      set_fact:
        deploy_app_group: "{{ deploy_app_user }}"
      when: deploy_app_group is not defined
  when: deploy_app_user is not defined

