- name: Remove temporary artifact dir
  file:
    path: "{{ deploy_artifact_temp_dir }}"
    state: absent

- name: Deuthorize deploy key
  authorized_key:
    user: "{{ deploy_app_user }}"
    key: "{{ lookup('file', deploy_ssh_key_path_pub) }}"
    state: absent