- name: Make sure generic map is configured
  lineinfile:
    dest: /etc/postfix/main.cf
    state: present
    backup: yes
    regexp: "^{{ item.name }}"
    line: "{{ item.name }} = {{ item.value }}"
  with_items:
    - { name: 'smtp_generic_maps', value: "hash:/etc/postfix/generic" }

- name: Add mail to generic map
  lineinfile:
    dest: /etc/postfix/generic
    state: present
    backup: yes
    regexp: "^{{ item.name }}"
    line: "{{ item.name }} {{ item.value }}"
  with_items:
    - { name: "{{ magento_user }}", value: "{{ magento_bounce_email_address }}" }

- name: Ensure map is encoded with postmap
  shell: "postmap /etc/postfix/generic"
  notify: Reload postfix

- name: Ensure sasl_passwd owner
  file:
    path: "/etc/postfix/{{ item }}"
    owner: postfix
  with_items:
    - "sasl_passwd"
    - "sasl_passwd.db"