nginx_remove_default_vhost: yes
nginx_client_max_body_size: 20M

# If you need to run custom PHP scripts from /pub you need to whitelist them here
# This is an nginx regexp, use something like:
# nginx_custom_php_scripts_path_pattern: '^/(script_name1|script_name2|scrip_prefix.*)\.php$'
nginx_custom_php_scripts_path_pattern: no

nginx_package: nginx
nginx_packages_extra: []

nginx_www_dir: "/var/www"
nginx_etc_dir: "/etc/nginx"
nginx_log_dir: "/var/log/nginx"
nginx_run_dir: "/var/run"
nginx_confd_dir: "{{ nginx_etc_dir }}/conf.d"

