- name: Get ElasticSuite version
  shell: "cat {{ magento_release_dir }}/composer.lock | jq '.packages | .[] | select(.name == \"smile/elasticsuite\") | .version'"
  register: _tmp_es_version

- name: Register ElasticSuite version
  set_fact:
    elasticsuite_version: "{{ _tmp_es_version.stdout | from_yaml }}"

- name: Register Dummy ElasticSuite version
  set_fact:
    elasticsuite_version: "0.0"
  when: elasticsuite_version is not defined or elasticsuite_version.strip() == ''

- name: Set legacy elasticsute config
  block:
    - name: Create configuration module directory
      file:
        path: "{{ magento_release_dir }}/app/code/Creativestyle/ElasticSuiteConfig/etc"
        owner: "{{ magento_user }}"
        group: "{{ magento_group }}"
        state: directory
        recurse: yes
        mode: "u=rwX,g=rX,o-rwx"

    - name: Create module.xml file
      template:
        src: elasticsuite_legacy/module.xml.j2
        dest: "{{ magento_release_dir }}/app/code/Creativestyle/ElasticSuiteConfig/etc/module.xml"
        owner: "{{ magento_user }}"
        group: "{{ magento_group }}"
        mode: 0640

    - name: Create config.xml file
      template:
        src: elasticsuite_legacy/config.xml.j2
        dest: "{{ magento_release_dir }}/app/code/Creativestyle/ElasticSuiteConfig/etc/config.xml"
        owner: "{{ magento_user }}"
        group: "{{ magento_group }}"
        mode: 0640

    - name: Create composer.json file
      template:
        src: elasticsuite_legacy/composer.json.j2
        dest: "{{ magento_release_dir }}/app/code/Creativestyle/ElasticSuiteConfig/composer.json"
        owner: "{{ magento_user }}"
        group: "{{ magento_group }}"
        mode: 0640

    - name: Create registration.php file
      template:
        src: elasticsuite_legacy/registration.php.j2
        dest: "{{ magento_release_dir }}/app/code/Creativestyle/ElasticSuiteConfig/registration.php"
        owner: "{{ magento_user }}"
        group: "{{ magento_group }}"
        mode: 0640
  when: elasticsuite_version is version('2.4', '<') and elasticsuite_version is version('2.0', '>')