### 
# Magento does it anyway during setup:upgrade, but lets make sure anyway.
# - Use `rm` because ansible cannot easily delete only contents in a
#   performant way, especially that this might be an s3fs mount.
# - Caution: This will not remove dotfiles, but we don't care.
###
- name: Make sure previous Mangeto static cache files are gone
  shell: "[[ ! -d '{{ magento_static_cache_dir }}' ]] || find '{{ magento_static_cache_dir }}' -xdev -type f -exec rm -vf {} \\;"
  args:
    warn: no
  changed_when: _magento_install_clean_statics.stdout | trim | length > 0
  register: _magento_install_clean_statics
  retries: 5
  delay: 10 
  until: not _magento_install_clean_statics is failed
  