- name: Make sure bash library directories exists
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0755
  with_items:
    - "{{ mageops_cli_bash_lib_upstream_dir }}"
    - "{{ mageops_cli_bash_lib_dir }}"

- name: Install upstream base bash library
  unarchive:
    src: "{{ mageops_cli_bash_lib_base_url }}"
    dest: "{{ mageops_cli_bash_lib_upstream_dir }}"
    remote_src: yes
    extra_opts: 
      - "--strip-components=1"

- name: Install mageops library sources
  copy:
    src: bash-lib/
    dest: "{{ mageops_cli_bash_lib_dir }}"
    remote_src: yes
    extra_opts: 
      - "--strip-components=1"