- name: Bind mount rootfs to temp dir
  mount:
    path: "{{ _s3fs_premount_temp_dir.path }}"
    src: "/"
    opts: bind
    fstype: none
    state: mounted

- name: Restore premount backup to new mountpoints
  shell: >
    rsync --archive \
          --verbose \
          --itemize-changes \
          --no-owner \
          --no-group \
          --no-times \
          --ignore-times \
          --ignore-existing \
          --inplace \
          --whole-file \
          --executability \
          --remove-source-files \
          '{{ s3fs_bind_mount.target.rstrip('/') }}/' \
          '{{ s3fs_bind_mount.source.rstrip('/') }}/'
  register: _s3fs_mountpoint_backup_restore_sync
  loop: "{{ s3fs_premount_bind_mounts }}"
  loop_control:
    loop_var: s3fs_bind_mount

- name: Print remount file restore log
  debug:
    var: _s3fs_mountpoint_backup_restore_sync.stdout_lines
