- name: Make sure backup root bind mount is absent
  mount:
    path: "{{ _s3fs_premount_temp_dir.path }}"
    src: "/"
    state: absent

- name: Remove backup mount temp dir
  file:
    path: "{{ _s3fs_premount_temp_dir.path }}"
    state: absent