- import_tasks: 001-create-premount-backups.yml

- name: Setup mounts
  block:
    - include_tasks: 002-setup-mounts.yml
    - include_tasks: 003-setup-watchdog.yml
    - include_tasks: 004-restore-premount-backups.yml
      when: s3fs_premount_bind_mounts | length
  always:
    - include_tasks: 005-cleanup.yml