allow_duplicates: no
dependencies: 
  - cs.repo-mageops

galaxy_info:
  author: Filip Sobalski <filip.sobalski@creativestyle.pl>
  description: Varnish repository for CentOS
  company: creativestyle Polska
  license: license (BSD, MIT)
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions: [7]
  galaxy_tags:
    - repository
    - packages
    - mageops
    - magento
    - magesuite
    - creativestyle
    - varnish
    - http
    - cache
    - caching
    - server


