- name: Configure nginx for Magento
  template:
    src: "{{ config.template }}"
    dest: "{{ config.filepath }}"
  loop:
    - template: "{{ nginx_magento_fastcgi_params_template }}"
      filepath: "{{ nginx_magento_fastcgi_params_conf_path }}"

    - template: "{{ nginx_magento_server_body_template }}"
      filepath: "{{ nginx_magento_server_body_conf_path }}"

    - template: "{{ nginx_magento_vhost_template }}"
      filepath: "{{ nginx_magento_vhost_conf_path }}"

    - template: magento_upstream.conf.j2
      filepath: "{{ nginx_fcgi_upstream_conf_file }}"

  loop_control:
    loop_var: config
    label: "{{ config.template }} -> {{ config.filepath }}"

  notify: Reload nginx
