- name: Install passlib
  pip:
    name: passlib

- name: Generate nginx htpasswdfile for site
  htpasswd:
    path: "{{ nginx_site_htpasswd_file }}"
    name: "{{ nginx_secure_site_user }}"
    password: "{{ nginx_secure_site_password }}"
    owner: root
    group: root
    mode: 0755
  when: nginx_secure_site

- name: Generate nginx htpasswdfile for cron
  htpasswd:
    path: "{{ nginx_cron_htpasswd_file }}"
    name: "{{ nginx_secure_cron_user }}"
    password: "{{ nginx_secure_cron_password }}"
    owner: root
    group: root
    mode: 0755
