##
# Warning! This task will only prepare nginx configuration partial for inclusion
# in vhost configuration. It will have no real effect besides creating this file.
#
# The inclusion shall happen in the actual nginx configuration roles.
#
# Warning! The map shall be included *outside* any server block. Inside the server
# you need to include the vhost check config partial.
#
# By default the map is added to nginx/conf.d dir so shall be included automatically.
##
- name: Make sure destination dirs exists
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ nginx_blacklist_map_config_file | dirname }}"
    - "{{ nginx_blacklist_vhost_check_config_file | dirname }}"

- name: Create URL blacklist main nginx config include
  template:
    src: magento_url_blacklist_map.j2
    dest: "{{ nginx_blacklist_map_config_file }}"
  notify: reload nginx


- name: Create URL blacklist vhost nginx config include
  template:
    src: magento_url_blacklist_check.j2
    dest: "{{ nginx_blacklist_vhost_check_config_file }}"
  notify: reload nginx