repo_mysql_package_name: mysql57-community-release
repo_mysql_name_prefix: mysql
repo_mysql_variants:
  - -connectors-community
  - -tools-community
  - -tools-preview
  - 55-community
  - 56-community
  - 57-community
  - 80-community

repo_mysql_variants_enabled:
  - -connectors-community
  - -tools-community
  - 57-community

