galaxy_info:
  author: creativestyle
  description: Autoscaling Varnish backends Manager for MageOps Infrastructure
  company: creativestyle Polska
  license: license (BSD, MIT)
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions: [7]
  galaxy_tags:
    - varnish
    - aws
    - autoscaling
    - webserver
    - server
    - http
    - proxy
    - mageops
    - magento
    - magesuite
    - creativestyle
